			
// Copyright 2006-2014 ClickTale Ltd., US Patent Pending
// PID: 8614
// Generated on: 7/26/2014 7:23:42 PM (UTC 7/27/2014 12:23:42 AM)

(function(){var e=!1,f=this;
function i(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==
b&&"undefined"==typeof a.call)return"object";return b};var l,m,n,o;function p(){return f.navigator?f.navigator.userAgent:null}o=n=m=l=e;var q;if(q=p()){var t=f.navigator;l=0==q.indexOf("Opera");m=!l&&-1!=q.indexOf("MSIE");n=!l&&-1!=q.indexOf("WebKit");o=!l&&!n&&"Gecko"==t.product}var u=l,v=m,w=o,x=n,y;
a:{var z="",A;if(u&&f.opera)var B=f.opera.version,z="function"==typeof B?B():B;else if(w?A=/rv\:([^\);]+)(\)|;)/:v?A=/MSIE\s+([^\);]+)(\)|;)/:x&&(A=/WebKit\/(\S+)/),A)var C=A.exec(p()),z=C?C[1]:"";if(v){var D,E=f.document;D=E?E.documentMode:void 0;if(D>parseFloat(z)){y=""+D;break a}}y=z}var F={};
function G(a){var b;if(!(b=F[a])){b=0;for(var c=(""+y).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),h=(""+a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=Math.max(c.length,h.length),g=0;0==b&&g<d;g++){var r=c[g]||"",X=h[g]||"",Y=RegExp("(\\d*)(\\D*)","g"),Z=RegExp("(\\d*)(\\D*)","g");do{var j=Y.exec(r)||["","",""],k=Z.exec(X)||["","",""];if(0==j[0].length&&0==k[0].length)break;b=((0==j[1].length?0:parseInt(j[1],10))<(0==k[1].length?0:parseInt(k[1],10))?-1:(0==j[1].length?0:parseInt(j[1],10))>
(0==k[1].length?0:parseInt(k[1],10))?1:0)||((0==j[2].length)<(0==k[2].length)?-1:(0==j[2].length)>(0==k[2].length)?1:0)||(j[2]<k[2]?-1:j[2]>k[2]?1:0)}while(0==b)}b=F[a]=0<=b}return b}var H={};function I(){H[9]||(H[9]=v&&!!document.documentMode&&9<=document.documentMode)};!v||I();!v||I();v&&G("8");!x||G("528");w&&G("1.9b")||v&&G("8")||u&&G("9.5")||x&&G("528");!w||G("8");function J(a){this.a=a}J.prototype.serialize=function(a){var b=[];K(this,a,b);return b.join("")};
function K(a,b,c){switch(typeof b){case "string":L(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if("array"==i(b)){var h=b.length;c.push("[");for(var d="",g=0;g<h;g++)c.push(d),d=b[g],K(a,a.a?a.a.call(b,""+g,d):d,c),d=",";c.push("]");break}c.push("{");h="";for(g in b)Object.prototype.hasOwnProperty.call(b,g)&&(d=b[g],"function"!=typeof d&&(c.push(h),L(g,c),c.push(":"),
K(a,a.a?a.a.call(b,g,d):d,c),h=","));c.push("}");break;case "function":break;default:throw Error("Unknown type: "+typeof b);}}var M={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},aa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function L(a,b){b.push('"',a.replace(aa,function(a){if(a in M)return M[a];var b=a.charCodeAt(0),d="\\u";16>b?d+="000":256>b?d+="00":4096>b&&(d+="0");return M[a]=d+b.toString(16)}),'"')};function N(a){"function"===typeof ClickTaleExec&&ClickTaleExec(a)}function O(a){"function"===typeof ClickTaleEvent&&ClickTaleEvent(a)}function P(a){"function"===typeof window.ClickTaleRegisterFormSubmit&&window.ClickTaleRegisterFormSubmit(a)}function Q(a,b){"function"===typeof window.ClickTaleRegisterElementAction&&ClickTaleRegisterElementAction(a,b)}window.ClickTaleDetectAgent&&window.ClickTaleDetectAgent()&&window.ClickTaleDetectAgent();var R="",S=document.location.pathname;function T(a,b,c){a.addEventListener?(a.addEventListener(b,c,e),T=function(a,b,c){a.addEventListener(b,c,e)}):a.attachEvent&&(a.attachEvent("on"+b,c),T=function(a,b,c){a.attachEvent("on"+b,c)})}function U(a,b){jQuery(document).one("mouseup",function(c){a===c.target&&b()})}
function V(a){if(!window.ClickTaleSettings||!window.ClickTaleSettings.ctBoolAgentXDR)N(a),V=N;else{var b=a.length;if(300>b)N(a);else{N('window.ctTempString="";');for(var b=Math.ceil(b/300),c=0;c<b;c++)N('window.ctTempString+="'+a.substring(300*c,300*(c+1))+'";');N("try { eval(window.ctTempString); } catch (e) { }")}}}function W(){jQuery("#ClickTaleDiv").append("<form></form>");W=function(){}}var ba={"/user/login/":"Login PopUp: ","/user/registration/":"Join Now PopUp: ","/user/forgotten-password/":"Forgot Password PopUp: "};
"/"===S?R="HomePage: ":top!=self&&(R=ba[S.toLowerCase()]);
setTimeout(function(){if(window.s&&window.s.eVar10){O("Page Type: "+window.s.eVar10);var a="";jQuery('[id^="keep-up-"]').map(function(b,c){var h=jQuery(c).html(),d=jQuery('[id^="keep-up-"]').index(c);a+="jQuery('[id^=\"keep-up-\"]').eq("+d+").html(unescape('"+escape(h)+"')); "});V(a)}0<jQuery('div[data-user-view="loggedIn"]:visible').length&&(R&&O(R+"Logged In User"),jQuery("#site-member > div").map(function(a,c){N("jQuery('#site-member > div').eq("+a+").css('display','"+jQuery(c).css("display")+
"');")}));top!=self&&R&&O(R.replace(/:/,""))},1E3);jQuery(document).on("dropdownshown dropdownhidden",function(a,b){if(b&&b.$element){var c=b.$element.prop("id"),h="dropdownshown"===a.type?"show":"hide";c&&N("try{jQuery('#"+c+"').data('dropdown')."+h+"();} catch(err){}")}});
top!=self?(jQuery(".modal-iframe[id^=uid-]").map(function(a,b){"function"===typeof window.ClickTaleSetCustomElementID&&window.ClickTaleSetCustomElementID(b,"uid-"+a)}),W(),jQuery(document).ajaxSuccess(function(a,b,c){-1!=c.url.search(/^https:\/\/secure\.techrepublic\.com\/user\/(login|forgotten-password|registration)/i)&&setTimeout(function(){if(jQuery("form.user-login,form.user-register,form.forgotten-password").get(0))var a=jQuery("form.user-login,form.user-register,form.forgotten-password").get(0);
else jQuery("body").append('<form id="ctTempId"></form>'),a=jQuery("body > form#ctTempId")[0];if(a)if(P(a),"function"===typeof window.ClickTaleRegisterFormSubmitSent&&window.ClickTaleRegisterFormSubmitSent(a),-1!=b.responseText.search(/"status":"success"/))"function"===typeof window.ClickTaleRegisterFormSubmitSuccess&&(a?window.ClickTaleRegisterFormSubmitSuccess(a):window.ClickTaleRegisterFormSubmitSuccess()),a===jQuery("body > form#ctTempId")[0]&&(a=jQuery(".modal-iframe .modal-body").html(),V("jQuery('.modal-iframe .modal-body').html(unescape('"+
escape(a)+"'));"));else if(-1!=b.responseText.search(/"status":"failure"/)){"function"===typeof window.ClickTaleRegisterFormSubmitFailure&&(a?window.ClickTaleRegisterFormSubmitFailure(a):window.ClickTaleRegisterFormSubmitFailure());var c=[];jQuery(".alert-error",jQuery("form.user-login,form.user-register,form.forgotten-password").get(0)).map(function(a,b){var h=jQuery(b).text();c.unshift(jQuery.trim(h))});N("jQuery(window).trigger('ct-"+jQuery("form.user-login,form.user-register,form.forgotten-password").attr("class")+
"-fail',["+(new J(void 0)).serialize(c)+"]);")}},300)}),jQuery(document).on("blur keyup input","form.user-login input,form.user-register input,form.forgotten-password input",function(){var a=this.id;a&&("user_email_email"!=a&&"user_email_confirm"!=a?N("jQuery('#"+a+"').change();"):setTimeout(function(){if(jQuery("#"+a).hasClass("validate-error")){var b=jQuery("#"+a).siblings("div").text();N("jQuery(window).trigger('ctValidErr', ['"+a+"', '"+escape(b)+"']);")}else N("jQuery(window).trigger('ctValidPass',['"+
a+"']);")},100))}),jQuery(document).on("change","#user_captchu, #user_country",function(){var a=jQuery(this).val(),b=this.id;"user_captchu"===b&&""!=a&&"robot"!=a&&(a="human");N("jQuery('#"+b+"').val('"+a+"').change();")})):jQuery(document).ajaxSend(function(a,b,c){-1!=c.url.search(/component\/load-more\/xhr/gi)&&R&&O(R+"Load More")});
jQuery(document).mousedown(function(a){var b=a.target,c=jQuery(b);Q("mouseover",a);0<c.closest("a.load-more").length?U(b,function(a,b){return function(){Q("mouseover",a);Q("click",a);var c=jQuery("a.load-more").index(b.closest("a.load-more"));N("jQuery('a.load-more').eq("+c+").click();");R&&O(R+"Load More")}}(a,c)):0<c.closest(".newsletter-list button.btn-primary").length&&U(b,function(a,b){return function(){Q("mouseover",a);Q("click",a);var c=jQuery(".newsletter-list button.btn-primary").index(b.closest(".newsletter-list button.btn-primary"));
N("jQuery('.newsletter-list button.btn-primary').eq("+c+").click();");c=b.closest(".newsletter-list button.btn-primary").text();R&&c&&O(R+jQuery.trim(c))}}(a,c))});
jQuery(document).click(function(a){var b=jQuery(a.target);if(0<b.closest(".horizaccordion section a.tab,span.next-arrow a,span.prev-arrow a").length){var c=jQuery(".horizaccordion section a.tab,span.next-arrow a,span.prev-arrow a").index(b.closest(".horizaccordion section a.tab,span.next-arrow a,span.prev-arrow a"));N("jQuery('.horizaccordion section a.tab,span.next-arrow a,span.prev-arrow a').eq("+c+").click();")}else if(0<b.closest('div[data-user-view="loggedOut"] a.nav-button').length)O(R+"Login"),
N("jQuery('div[data-user-view=\"loggedOut\"] a.nav-button').click();");else if(0<b.closest('#article-river a[href="#tab-content-1"]').length)c=jQuery('#article-river a[href="#tab-content-1"]').index(b.closest('#article-river a[href="#tab-content-1"]')),N("jQuery('#article-river a[href=\"#tab-content-1\"]').eq("+c+").click();"),a=b.closest('#article-river a[href="#tab-content-1"]').text(),R&&a&&O(R+jQuery.trim(a));else if(top!=self)if(0<b.closest("form button.btn.btn-primary").length)a=b.closest("form button.btn.btn-primary").text(),
R&&a&&O(R+jQuery.trim(a)),-1!=S.search(/\/user\/registration\//i)&&(window.ClickTaleSettings.ElementPathRewriter=function(a,b){a===document.getElementById("dynamic_registration")&&(window.ClickTaleSettings.ctTempRegisterFormPath=b);return b},jQuery(".modal-iframe form.user-login,form.user-register,form.forgotten-password").click(),window.ClickTaleSettings.ElementPathRewriter=function(a,b){return a===jQuery("body > form#ctTempId")[0]&&window.ClickTaleSettings.ctTempRegisterFormPath?window.ClickTaleSettings.ctTempRegisterFormPath:
b}),N("jQuery('form .alert-error').parent().remove();"),setTimeout(function(){if(0<jQuery(".validate-error").length){N("jQuery('form button.btn.btn-primary').click();");var a=b.closest("form").get(0);a&&(P(a),"function"===typeof window.ClickTaleRegisterFormSubmitNotSent&&window.ClickTaleRegisterFormSubmitNotSent(a))}},100);else if(0<b.closest(".btn-newsletter-sub,.btn-group a.btn").length){var a=b.text(),h=b.closest(".btn-newsletter-sub,.btn-group a.btn");R&&a&&O(R+jQuery.trim(a));c=jQuery(".btn-newsletter-sub,.btn-group a.btn").index(h);
jQuery(document).one("ajaxComplete",function(a,b,d){-1!=d.url.search(/newsletters\/xhr\/subscription\/\?(un)?subs/)&&N("jQuery('.btn-newsletter-sub,.btn-group a.btn').eq("+c+").attr('class', '"+h.attr("class")+"').text('"+h.text()+"');")})}else if(b.is(".checkbox label[for]")){var d={},g=jQuery("#"+b.attr("for")).get(0),r;for(r in a)d[r]=a[r];g&&(d.srcElement=g,d.target=g);Q("mouseover",d);Q("click",d);Q("mouseover",a)}});
T(window,"message",function(a){a.data&&"https://secure.techrepublic.com"===a.origin?(-1!=a.data.search(/{"name":"closeModal"}/i)&&a.source&&(N("try { jQuery('.modal:visible').data('modalIframe').close(); } catch (err) { }"),a.source.postMessage&&a.source.postMessage("ClickTaleStop",a.origin)),-1!=a.data.search(/{"name":"(loginSuccess|loginSubmitted)"/i)&&a.source&&N("try { jQuery('.modal:visible').data('modalIframe').close(); } catch (err) { }"),jQuery("#site-member > div").map(function(a,c){N("jQuery('#site-member > div').eq("+
a+").css('display','"+jQuery(c).css("display")+"');")})):a.data&&"http://www.techrepublic.com"===a.origin&&"ClickTaleStop"===a.data&&"function"===typeof ClickTaleStop&&ClickTaleStop()});
jQuery(document).ready(function(){if("/user/registration/"==window.location.pathname){var a=e;jQuery("form button").mouseup(function(){setTimeout(function(){if((0<jQuery(".validate-error:visible").length||0<jQuery(".alert-error:visible").length)&&!a)a=!0,O("Client Side Validation Error Appears")},1500)});jQuery("form input, form select").blur(function(){setTimeout(function(){0<jQuery(".validate-error:visible").length&&!a&&(a=!0,O("Client Side Validation Error Appears"))},800)})}});})();

